#!/usr/bin/env python3
"""Decode a WiCAN data_logger `.wdl` binary log.

Format ("WDL1" magic, little-endian, self-contained — the param
dictionary is inline; a resumed file may carry several dictionary
blocks, each def applies to the records after it):

  0x01 def:   u16 id, u8 len, name bytes ("source.name")
  0x02 param: i64 ts_ms, u16 id, f64 value
  0x03 frame: i64 ts_ms, u32 id_word, u8 dlc, data[dlc]
              id_word bit31 = extended id, bit30 = RTR

Output formats:
  csv     params: ts_ms,param,value  /  frames: ts_ms,id,ext,rtr,dlc,data
  candump (frames only) "(ts.sec) can0 ID#HEXDATA" — SavvyCAN/canutils
  trc     (frames only) PEAK PCAN-View v1.1 text trace
  text    human-readable mixed dump (default)

  python wdl_dump.py file.wdl [--to csv|candump|trc|text] [--strict]

--strict exits 1 on a torn/unknown tail instead of stopping quietly
(a torn tail frame is legal — power loss mid-write).
"""
import argparse
import struct
import sys


def decode(path, strict=False):
    """Yield ('param', ts_ms, name, value) / ('frame', ts_ms, id, ext,
    rtr, data_bytes) tuples."""
    with open(path, "rb") as f:
        blob = f.read()

    if blob[:4] != b"WDL1":
        raise SystemExit(f"{path}: not a WDL1 file")

    names = {}
    off = 4
    end = len(blob)

    while off < end:
        rtype = blob[off]
        off += 1
        try:
            if rtype == 0x01:
                pid, nlen = struct.unpack_from("<HB", blob, off)
                off += 3
                name = blob[off:off + nlen].decode("utf-8", "replace")
                if len(blob[off:off + nlen]) != nlen:
                    raise struct.error("torn def")
                off += nlen
                names[pid] = name
            elif rtype == 0x02:
                ts, pid, value = struct.unpack_from("<qHd", blob, off)
                off += 18
                yield ("param", ts, names.get(pid, f"?{pid}"), value)
            elif rtype == 0x03:
                ts, idw, dlc = struct.unpack_from("<qIB", blob, off)
                off += 13
                data = blob[off:off + dlc]
                if len(data) != dlc:
                    raise struct.error("torn frame")
                off += dlc
                yield ("frame", ts, idw & 0x1FFFFFFF,
                       bool(idw & 0x80000000), bool(idw & 0x40000000),
                       data)
            else:
                raise struct.error(f"unknown record type 0x{rtype:02X}")
        except struct.error as e:
            if strict:
                raise SystemExit(f"{path}: {e} at offset {off - 1}")
            return  # torn tail — normal after power loss


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("file")
    ap.add_argument("--to", choices=("csv", "candump", "trc", "text"),
                    default="text")
    ap.add_argument("--strict", action="store_true")
    a = ap.parse_args()

    n_params = n_frames = 0
    trc_base = None

    for rec in decode(a.file, a.strict):
        if a.to == "trc" and rec[0] == "frame" and trc_base is None:
            trc_base = rec[1]
            # OLE automation date = days since 1899-12-30
            print(";$FILEVERSION=1.1")
            print(f";$STARTTIME={trc_base / 86400000 + 25569:.10f}")
            print(";   Generated by WiCAN wdl_dump")
        if rec[0] == "param":
            _, ts, name, value = rec
            n_params += 1
            if a.to == "csv":
                print(f"{ts},{name},{value:.6g}")
            elif a.to == "text":
                print(f"{ts} {name} = {value:.6g}")
        else:
            _, ts, fid, ext, rtr, data = rec
            n_frames += 1
            if a.to == "csv":
                print(f"{ts},{fid:X},{int(ext)},{int(rtr)},"
                      f"{len(data)},{data.hex().upper()}")
            elif a.to == "candump":
                ident = f"{fid:08X}" if ext else f"{fid:03X}"
                body = "R" if rtr else data.hex().upper()
                print(f"({ts / 1000:.3f}) can0 {ident}#{body}")
            elif a.to == "trc":
                ident = f"{fid:08X}" if ext else f"{fid:04X}"
                body = "RTR" if rtr else \
                    " ".join(f"{b:02X}" for b in data)
                print(f"{n_frames:6d}) {ts - trc_base:10.1f}  Rx  "
                      f"{ident}  {len(data)}  {body}")
            else:
                flags = ("X" if ext else "") + ("R" if rtr else "")
                print(f"{ts} 0x{fid:X}{flags} [{len(data)}] "
                      f"{data.hex().upper()}")

    if a.to == "text":
        print(f"-- {n_params} params, {n_frames} frames")


if __name__ == "__main__":
    main()
